--- Used to config the spawn generation settings yes there is alot here i know just ignore the long tables at the end (they were generated with a command)
-- @config Spawn-Area

return {
	spawn_area = {
		deconstruction_radius = 20,
		deconstruction_tile = nil,
		tile_radius = 20,
		landfill_radius = 50,
	},
	turrets = {                          --- @setting infinite_ammo_turrets These turrets will have they ammo refilled automatically and can not be looted
		enabled = true,                  --- @setting enabled weather the turrets will be created and refilled
		ammo_type = 'uranium-rounds-magazine', --- @setting ammo_type the ammo type that will be used
		offset = { x = 0, y = -1 },
		refill_time = 60 * 60 * 5,
		locations = { --- @setting locations locations of all turrets, this is default it can be changed during runtime
			{ surface = 1, position = { x = -12, y = -3 } },
			{ surface = 1, position = { x = 12, y = -3 } },
			{ surface = 1, position = { x = -12, y = 4 } },
			{ surface = 1, position = { x = 12, y = 4 } }
		}
	},
	afk_belts = {  --- @setting afk_belts setting relating to afk belts round the spawn point
		enabled = false, --- @setting enabled weather afk belts will be generated
		offset = { x = -2, y = 8 },
		locations = { --- @setting locations top left connors of any afk belt loops to be added
			{ x = 12,  y = 9 },
			{ x = -12, y = 9 },
			{ x = 12,  y = -9 },
			{ x = -12, y = -9 }
		}
	},

	water = {
		enabled = false
	},
	entities = { --- @setting entities All entities that will be created as part of spawn {entity-name,x-pos,y-pos}
		enabled = true,
		offset = { x = 0, y = -1 },
		protected = true,
		operable = true,
		locations = {
			{"stone-wall",-13.5,-3.5},
			{"stone-wall",-12.5,-4.5},
			{"stone-wall",-13.5,-4.5},
			{"iron-chest",-10.5,-3.5},
			{"stone-wall",-10.5,-4.5},
			{"stone-wall",-11.5,-4.5},
			{"iron-chest",-9.5,-3.5},
			{"iron-chest",-8.5,-3.5},
			{"stone-wall",-8.5,-4.5},
			{"stone-wall",-9.5,-4.5},
			{"iron-chest",-7.5,-3.5},
			{"iron-chest",-6.5,-3.5},
			{"stone-wall",-6.5,-4.5},
			{"stone-wall",-7.5,-4.5},
			{"iron-chest",-5.5,-3.5},
			{"stone-wall",-4.5,-4.5},
			{"stone-wall",-5.5,-4.5},
			{"stone-wall",-3.5,-4.5},
			{"stone-wall",3.5,-4.5},
			{"iron-chest",5.5,-3.5},
			{"stone-wall",5.5,-4.5},
			{"stone-wall",4.5,-4.5},
			{"iron-chest",7.5,-3.5},
			{"iron-chest",6.5,-3.5},
			{"stone-wall",7.5,-4.5},
			{"stone-wall",6.5,-4.5},
			{"iron-chest",9.5,-3.5},
			{"iron-chest",8.5,-3.5},
			{"stone-wall",9.5,-4.5},
			{"stone-wall",8.5,-4.5},
			{"iron-chest",10.5,-3.5},
			{"stone-wall",11.5,-4.5},
			{"stone-wall",10.5,-4.5},
			{"stone-wall",13.5,-3.5},
			{"stone-wall",12.5,-4.5},
			{"stone-wall",13.5,-4.5},
			{"stone-wall",-13.5,-1.5},
			{"stone-wall",-13.5,-2.5},
			{"stone-wall",13.5,-1.5},
			{"stone-wall",13.5,-2.5},
			{"stone-wall",-13.5,2.5},
			{"stone-wall",13.5,2.5},
			{"stone-wall",-13.5,4.5},
			{"stone-wall",-13.5,3.5},
			{"iron-chest",-10.5,4.5},
			{"iron-chest",-9.5,4.5},
			{"iron-chest",-8.5,4.5},
			{"iron-chest",-7.5,4.5},
			{"iron-chest",-6.5,4.5},
			{"iron-chest",-5.5,4.5},
			{"iron-chest",5.5,4.5},
			{"iron-chest",7.5,4.5},
			{"iron-chest",6.5,4.5},
			{"iron-chest",9.5,4.5},
			{"iron-chest",8.5,4.5},
			{"iron-chest",10.5,4.5},
			{"stone-wall",13.5,4.5},
			{"stone-wall",13.5,3.5},
			{"stone-wall",-13.5,5.5},
			{"stone-wall",-12.5,5.5},
			{"stone-wall",-10.5,5.5},
			{"stone-wall",-11.5,5.5},
			{"stone-wall",-8.5,5.5},
			{"stone-wall",-9.5,5.5},
			{"stone-wall",-7.5,5.5},
			{"stone-wall",-6.5,5.5},
			{"stone-wall",-4.5,5.5},
			{"stone-wall",-5.5,5.5},
			{"stone-wall",-3.5,5.5},
			{"stone-wall",3.5,5.5},
			{"stone-wall",4.5,5.5},
			{"stone-wall",5.5,5.5},
			{"stone-wall",6.5,5.5},
			{"stone-wall",7.5,5.5},
			{"stone-wall",8.5,5.5},
			{"stone-wall",9.5,5.5},
			{"stone-wall",10.5,5.5},
			{"stone-wall",11.5,5.5},
			{"stone-wall",12.5,5.5},
			{"stone-wall",13.5,5.5},
		}
	},
	pattern = { --- @setting tiles The location of the "pattern" tiles {x-pos,y-pos}
		enabled = true,
		offset = { x = 0, y = -1 },
		locations = {
			{ name = "concrete", position = { x = -14, y = -5 } }, { name = "concrete", position = { x = -14, y = -4 } },
			{ name = "concrete", position = { x = -14, y = -3 } }, { name = "concrete", position = { x = -14, y = -2 } },
			{ name = "refined-concrete", position = { x = -14, y = -1 } },
			{ name = "refined-concrete", position = { x = -14, y = 0 } },
			{ name = "refined-concrete", position = { x = -14, y = 1 } },
			{ name = "concrete",         position = { x = -14, y = 2 } },
			{ name = "concrete",         position = { x = -14, y = 3 } },
			{ name = "concrete",         position = { x = -14, y = 4 } },
			{ name = "concrete",         position = { x = -14, y = 5 } },
			{ name = "concrete",         position = { x = -13, y = -5 } },
			{ name = "refined-concrete", position = { x = -13, y = -4 } },
			{ name = "refined-concrete", position = { x = -13, y = -3 } },
			{ name = "refined-concrete", position = { x = -13, y = -2 } },
			{ name = "refined-concrete", position = { x = -13, y = -1 } },
			{ name = "refined-concrete", position = { x = -13, y = 0 } },
			{ name = "refined-concrete", position = { x = -13, y = 1 } },
			{ name = "refined-concrete", position = { x = -13, y = 2 } },
			{ name = "refined-concrete", position = { x = -13, y = 3 } },
			{ name = "refined-concrete", position = { x = -13, y = 4 } },
			{ name = "concrete",         position = { x = -13, y = 5 } },
			{ name = "concrete",         position = { x = -12, y = -5 } },
			{ name = "refined-concrete", position = { x = -12, y = -4 } },
			{ name = "concrete",         position = { x = -12, y = -3 } },
			{ name = "concrete",         position = { x = -12, y = -2 } },
			{ name = "concrete",         position = { x = -12, y = -1 } },
			{ name = "concrete", position = { x = -12, y = 0 } },
			{ name = "concrete",                     position = { x = -12, y = 1 } },
			{ name = "concrete", position = { x = -12, y = 2 } },
			{ name = "concrete",                     position = { x = -12, y = 3 } },
			{ name = "refined-concrete",             position = { x = -12, y = 4 } },
			{ name = "concrete",                     position = { x = -12, y = 5 } },
			{ name = "concrete",                     position = { x = -11, y = -5 } },
			{ name = "refined-concrete",             position = { x = -11, y = -4 } },
			{ name = "concrete",                     position = { x = -11, y = -3 } },
			{ name = "concrete",                     position = { x = -11, y = -2 } },
			{ name = "refined-hazard-concrete-left", position = { x = -11, y = -1 } },
			{ name = "refined-hazard-concrete-left", position = { x = -11, y = 0 } },
			{ name = "refined-hazard-concrete-left", position = { x = -11, y = 1 } },
			{ name = "refined-hazard-concrete-left", position = { x = -11, y = 2 } },
			{ name = "concrete",                     position = { x = -11, y = 3 } },
			{ name = "refined-concrete",             position = { x = -11, y = 4 } },
			{ name = "concrete",                     position = { x = -11, y = 5 } },
			{ name = "concrete",                     position = { x = -10, y = -5 } },
			{ name = "refined-concrete",             position = { x = -10, y = -4 } },
			{ name = "concrete",                     position = { x = -10, y = -3 } },
			{ name = "refined-hazard-concrete-left", position = { x = -10, y = -2 } },
			{ name = "concrete",                     position = { x = -10, y = -1 } },
			{ name = "refined-hazard-concrete-left", position = { x = -10, y = 0 } },
			{ name = "concrete",                     position = { x = -10, y = 1 } },
			{ name = "concrete",                     position = { x = -10, y = 2 } },
			{ name = "concrete",                     position = { x = -10, y = 3 } },
			{ name = "refined-concrete",             position = { x = -10, y = 4 } },
			{ name = "concrete",                     position = { x = -10, y = 5 } },
			{ name = "concrete",                     position = { x = -9, y = -5 } },
			{ name = "refined-concrete",             position = { x = -9, y = -4 } },
			{ name = "concrete",                     position = { x = -9, y = -3 } },
			{ name = "concrete",                     position = { x = -9, y = -2 } },
			{ name = "refined-hazard-concrete-left", position = { x = -9, y = -1 } },
			{ name = "refined-hazard-concrete-left", position = { x = -9, y = 0 } },
			{ name = "refined-hazard-concrete-left", position = { x = -9, y = 1 } },
			{ name = "refined-hazard-concrete-left", position = { x = -9, y = 2 } },
			{ name = "concrete",                     position = { x = -9, y = 3 } },
			{ name = "refined-concrete",             position = { x = -9, y = 4 } },
			{ name = "concrete",                     position = { x = -9, y = 5 } },
			{ name = "concrete",                     position = { x = -8, y = -5 } },
			{ name = "refined-concrete",             position = { x = -8, y = -4 } },
			{ name = "concrete",                     position = { x = -8, y = -3 } },
			{ name = "concrete",                     position = { x = -8, y = -2 } },
			{ name = "concrete",                     position = { x = -8, y = -1 } },
			{ name = "concrete", position = { x = -8, y = 0 } },
			{ name = "concrete",                     position = { x = -8, y = 1 } },
			{ name = "concrete", position = { x = -8, y = 2 } },
			{ name = "concrete",                     position = { x = -8, y = 3 } },
			{ name = "refined-concrete",             position = { x = -8, y = 4 } },
			{ name = "concrete",                     position = { x = -8, y = 5 } },
			{ name = "concrete",                     position = { x = -7, y = -5 } },
			{ name = "refined-concrete",             position = { x = -7, y = -4 } },
			{ name = "concrete",                     position = { x = -7, y = -3 } },
			{ name = "refined-hazard-concrete-left", position = { x = -7, y = -2 } },
			{ name = "refined-hazard-concrete-left", position = { x = -7, y = -1 } },
			{ name = "refined-hazard-concrete-left", position = { x = -7, y = 0 } },
			{ name = "refined-hazard-concrete-left", position = { x = -7, y = 1 } },
			{ name = "concrete",                     position = { x = -7, y = 2 } },
			{ name = "concrete",                     position = { x = -7, y = 3 } },
			{ name = "refined-concrete",             position = { x = -7, y = 4 } },
			{ name = "concrete",                     position = { x = -7, y = 5 } },
			{ name = "concrete",                     position = { x = -6, y = -5 } },
			{ name = "refined-concrete",             position = { x = -6, y = -4 } },
			{ name = "concrete",                     position = { x = -6, y = -3 } },
			{ name = "concrete",                     position = { x = -6, y = -2 } },
			{ name = "concrete",                     position = { x = -6, y = -1 } },
			{ name = "concrete",                     position = { x = -6, y = 0 } },
			{ name = "concrete",                     position = { x = -6, y = 1 } },
			{ name = "refined-hazard-concrete-left", position = { x = -6, y = 2 } },
			{ name = "concrete",                     position = { x = -6, y = 3 } },
			{ name = "refined-concrete",             position = { x = -6, y = 4 } },
			{ name = "concrete",                     position = { x = -6, y = 5 } },
			{ name = "concrete",                     position = { x = -5, y = -5 } },
			{ name = "refined-concrete",             position = { x = -5, y = -4 } },
			{ name = "concrete",                     position = { x = -5, y = -3 } },
			{ name = "refined-hazard-concrete-left", position = { x = -5, y = -2 } },
			{ name = "refined-hazard-concrete-left", position = { x = -5, y = -1 } },
			{ name = "refined-hazard-concrete-left", position = { x = -5, y = 0 } },
			{ name = "refined-hazard-concrete-left", position = { x = -5, y = 1 } },
			{ name = "concrete",                     position = { x = -5, y = 2 } },
			{ name = "concrete",                     position = { x = -5, y = 3 } },
			{ name = "refined-concrete",             position = { x = -5, y = 4 } },
			{ name = "concrete",                     position = { x = -5, y = 5 } },
			{ name = "concrete",                     position = { x = -4, y = -5 } },
			{ name = "refined-concrete",             position = { x = -4, y = -4 } },
			{ name = "concrete",                     position = { x = -4, y = -3 } },
			{ name = "concrete",                     position = { x = -4, y = -2 } },
			{ name = "concrete",                     position = { x = -4, y = -1 } },
			{ name = "concrete",                     position = { x = -4, y = 0 } },
			{ name = "concrete",                     position = { x = -4, y = 1 } },
			{ name = "refined-hazard-concrete-left", position = { x = -4, y = 2 } },
			{ name = "concrete",                     position = { x = -4, y = 3 } },
			{ name = "refined-concrete",             position = { x = -4, y = 4 } },
			{ name = "concrete",                     position = { x = -4, y = 5 } },
			{ name = "concrete",                     position = { x = -3, y = -5 } },
			{ name = "refined-concrete",             position = { x = -3, y = -4 } },
			{ name = "concrete",                     position = { x = -3, y = -3 } },
			{ name = "refined-hazard-concrete-left", position = { x = -3, y = -2 } },
			{ name = "refined-hazard-concrete-left", position = { x = -3, y = -1 } },
			{ name = "refined-hazard-concrete-left", position = { x = -3, y = 0 } },
			{ name = "refined-hazard-concrete-left", position = { x = -3, y = 1 } },
			{ name = "concrete",                     position = { x = -3, y = 2 } },
			{ name = "concrete",                     position = { x = -3, y = 3 } },
			{ name = "refined-concrete",             position = { x = -3, y = 4 } },
			{ name = "concrete",                     position = { x = -3, y = 5 } },
			{ name = "refined-concrete",             position = { x = -2, y = -5 } },
			{ name = "refined-concrete",             position = { x = -2, y = -4 } },
			{ name = "concrete",                     position = { x = -2, y = -3 } },
			{ name = "concrete",                     position = { x = -2, y = -2 } },
			{ name = "concrete",                     position = { x = -2, y = -1 } },
			{ name = "concrete", position = { x = -2, y = 0 } },
			{ name = "concrete",                     position = { x = -2, y = 1 } },
			{ name = "concrete", position = { x = -2, y = 2 } },
			{ name = "concrete",                     position = { x = -2, y = 3 } },
			{ name = "refined-hazard-concrete-left", position = { x = -2, y = 4 } },
			{ name = "refined-hazard-concrete-left", position = { x = -2, y = 5 } },
			{ name = "refined-concrete",             position = { x = -1, y = -5 } },
			{ name = "refined-concrete",             position = { x = -1, y = -4 } },
			{ name = "concrete",                     position = { x = -1, y = -3 } },
			{ name = "refined-hazard-concrete-left", position = { x = -1, y = -2 } },
			{ name = "refined-hazard-concrete-left", position = { x = -1, y = -1 } },
			{ name = "refined-hazard-concrete-left", position = { x = -1, y = 0 } },
			{ name = "refined-hazard-concrete-left", position = { x = -1, y = 1 } },
			{ name = "refined-hazard-concrete-left", position = { x = -1, y = 2 } },
			{ name = "concrete",                     position = { x = -1, y = 3 } },
			{ name = "refined-hazard-concrete-left", position = { x = -1, y = 4 } },
			{ name = "refined-hazard-concrete-left", position = { x = -1, y = 5 } },
			{ name = "refined-concrete",             position = { x = 0, y = -5 } },
			{ name = "refined-concrete",             position = { x = 0, y = -4 } },
			{ name = "concrete",                     position = { x = 0, y = -3 } },
			{ name = "refined-hazard-concrete-left", position = { x = 0, y = -2 } },
			{ name = "concrete",                     position = { x = 0, y = -1 } },
			{ name = "refined-hazard-concrete-left", position = { x = 0, y = 0 } },
			{ name = "concrete",                     position = { x = 0, y = 1 } },
			{ name = "concrete",                     position = { x = 0, y = 2 } },
			{ name = "concrete",                     position = { x = 0, y = 3 } },
			{ name = "refined-hazard-concrete-left", position = { x = 0, y = 4 } },
			{ name = "refined-hazard-concrete-left", position = { x = 0, y = 5 } },
			{ name = "refined-concrete",             position = { x = 1, y = -5 } },
			{ name = "refined-concrete",             position = { x = 1, y = -4 } },
			{ name = "concrete",                     position = { x = 1, y = -3 } },
			{ name = "refined-hazard-concrete-left", position = { x = 1, y = -2 } },
			{ name = "concrete",                     position = { x = 1, y = -1 } },
			{ name = "concrete",                     position = { x = 1, y = 0 } },
			{ name = "concrete",                     position = { x = 1, y = 1 } },
			{ name = "concrete",                     position = { x = 1, y = 2 } },
			{ name = "concrete",                     position = { x = 1, y = 3 } },
			{ name = "refined-hazard-concrete-left", position = { x = 1, y = 4 } },
			{ name = "refined-hazard-concrete-left", position = { x = 1, y = 5 } },
			{ name = "concrete",                     position = { x = 2, y = -5 } },
			{ name = "refined-concrete",             position = { x = 2, y = -4 } },
			{ name = "concrete",                     position = { x = 2, y = -3 } },
			{ name = "concrete",                     position = { x = 2, y = -2 } },
			{ name = "concrete",                     position = { x = 2, y = -1 } },
			{ name = "concrete",                     position = { x = 2, y = 0 } },
			{ name = "concrete",                     position = { x = 2, y = 1 } },
			{ name = "refined-hazard-concrete-left", position = { x = 2, y = 2 } },
			{ name = "concrete",                     position = { x = 2, y = 3 } },
			{ name = "refined-concrete",             position = { x = 2, y = 4 } },
			{ name = "concrete",                     position = { x = 2, y = 5 } },
			{ name = "concrete",                     position = { x = 3, y = -5 } },
			{ name = "refined-concrete",             position = { x = 3, y = -4 } },
			{ name = "concrete",                     position = { x = 3, y = -3 } },
			{ name = "concrete",                     position = { x = 3, y = -2 } },
			{ name = "concrete",                     position = { x = 3, y = -1 } },
			{ name = "concrete", position = { x = 3, y = 0 } },
			{ name = "concrete",                     position = { x = 3, y = 1 } },
			{ name = "concrete", position = { x = 3, y = 2 } },
			{ name = "concrete",                     position = { x = 3, y = 3 } },
			{ name = "refined-concrete",             position = { x = 3, y = 4 } },
			{ name = "concrete",                     position = { x = 3, y = 5 } },
			{ name = "concrete",                     position = { x = 4, y = -5 } },
			{ name = "refined-concrete",             position = { x = 4, y = -4 } },
			{ name = "concrete",                     position = { x = 4, y = -3 } },
			{ name = "refined-hazard-concrete-left", position = { x = 4, y = -2 } },
			{ name = "refined-hazard-concrete-left", position = { x = 4, y = -1 } },
			{ name = "refined-hazard-concrete-left", position = { x = 4, y = 0 } },
			{ name = "concrete",                     position = { x = 4, y = 1 } },
			{ name = "refined-hazard-concrete-left", position = { x = 4, y = 2 } },
			{ name = "concrete",                     position = { x = 4, y = 3 } },
			{ name = "refined-concrete",             position = { x = 4, y = 4 } },
			{ name = "concrete",                     position = { x = 4, y = 5 } },
			{ name = "concrete",                     position = { x = 5, y = -5 } },
			{ name = "refined-concrete",             position = { x = 5, y = -4 } },
			{ name = "concrete",                     position = { x = 5, y = -3 } },
			{ name = "concrete",                     position = { x = 5, y = -2 } },
			{ name = "concrete",                     position = { x = 5, y = -1 } },
			{ name = "refined-hazard-concrete-left", position = { x = 5, y = 0 } },
			{ name = "concrete",                     position = { x = 5, y = 1 } },
			{ name = "refined-hazard-concrete-left", position = { x = 5, y = 2 } },
			{ name = "concrete",                     position = { x = 5, y = 3 } },
			{ name = "refined-concrete",             position = { x = 5, y = 4 } },
			{ name = "concrete",                     position = { x = 5, y = 5 } },
			{ name = "concrete",                     position = { x = 6, y = -5 } },
			{ name = "refined-concrete",             position = { x = 6, y = -4 } },
			{ name = "concrete",                     position = { x = 6, y = -3 } },
			{ name = "refined-hazard-concrete-left", position = { x = 6, y = -2 } },
			{ name = "refined-hazard-concrete-left", position = { x = 6, y = -1 } },
			{ name = "refined-hazard-concrete-left", position = { x = 6, y = 0 } },
			{ name = "refined-hazard-concrete-left", position = { x = 6, y = 1 } },
			{ name = "refined-hazard-concrete-left", position = { x = 6, y = 2 } },
			{ name = "concrete",                     position = { x = 6, y = 3 } },
			{ name = "refined-concrete",             position = { x = 6, y = 4 } },
			{ name = "concrete",                     position = { x = 6, y = 5 } },
			{ name = "concrete",                     position = { x = 7, y = -5 } },
			{ name = "refined-concrete",             position = { x = 7, y = -4 } },
			{ name = "concrete",                     position = { x = 7, y = -3 } },
			{ name = "concrete",                     position = { x = 7, y = -2 } },
			{ name = "concrete",                     position = { x = 7, y = -1 } },
			{ name = "concrete", position = { x = 7, y = 0 } },
			{ name = "concrete",                     position = { x = 7, y = 1 } },
			{ name = "concrete", position = { x = 7, y = 2 } },
			{ name = "concrete",                     position = { x = 7, y = 3 } },
			{ name = "refined-concrete",             position = { x = 7, y = 4 } },
			{ name = "concrete",                     position = { x = 7, y = 5 } },
			{ name = "concrete",                     position = { x = 8, y = -5 } },
			{ name = "refined-concrete",             position = { x = 8, y = -4 } },
			{ name = "concrete",                     position = { x = 8, y = -3 } },
			{ name = "refined-hazard-concrete-left", position = { x = 8, y = -2 } },
			{ name = "concrete",                     position = { x = 8, y = -1 } },
			{ name = "concrete",                     position = { x = 8, y = 0 } },
			{ name = "concrete",                     position = { x = 8, y = 1 } },
			{ name = "concrete",                     position = { x = 8, y = 2 } },
			{ name = "concrete",                     position = { x = 8, y = 3 } },
			{ name = "refined-concrete",             position = { x = 8, y = 4 } },
			{ name = "concrete",                     position = { x = 8, y = 5 } },
			{ name = "concrete",                     position = { x = 9, y = -5 } },
			{ name = "refined-concrete",             position = { x = 9, y = -4 } },
			{ name = "concrete",                     position = { x = 9, y = -3 } },
			{ name = "refined-hazard-concrete-left", position = { x = 9, y = -2 } },
			{ name = "refined-hazard-concrete-left", position = { x = 9, y = -1 } },
			{ name = "refined-hazard-concrete-left", position = { x = 9, y = 0 } },
			{ name = "refined-hazard-concrete-left", position = { x = 9, y = 1 } },
			{ name = "refined-hazard-concrete-left", position = { x = 9, y = 2 } },
			{ name = "concrete",                     position = { x = 9, y = 3 } },
			{ name = "refined-concrete",             position = { x = 9, y = 4 } },
			{ name = "concrete",                     position = { x = 9, y = 5 } },
			{ name = "concrete",                     position = { x = 10, y = -5 } },
			{ name = "refined-concrete",             position = { x = 10, y = -4 } },
			{ name = "concrete",                     position = { x = 10, y = -3 } },
			{ name = "refined-hazard-concrete-left", position = { x = 10, y = -2 } },
			{ name = "concrete",                     position = { x = 10, y = -1 } },
			{ name = "concrete",                     position = { x = 10, y = 0 } },
			{ name = "concrete",                     position = { x = 10, y = 1 } },
			{ name = "concrete",                     position = { x = 10, y = 2 } },
			{ name = "concrete",                     position = { x = 10, y = 3 } },
			{ name = "refined-concrete",             position = { x = 10, y = 4 } },
			{ name = "concrete",                     position = { x = 10, y = 5 } },
			{ name = "concrete",                     position = { x = 11, y = -5 } },
			{ name = "refined-concrete",             position = { x = 11, y = -4 } },
			{ name = "concrete",                     position = { x = 11, y = -3 } },
			{ name = "concrete",                     position = { x = 11, y = -2 } },
			{ name = "concrete",                     position = { x = 11, y = -1 } },
			{ name = "concrete", position = { x = 11, y = 0 } },
			{ name = "concrete",         position = { x = 11, y = 1 } },
			{ name = "concrete", position = { x = 11, y = 2 } },
			{ name = "concrete",         position = { x = 11, y = 3 } },
			{ name = "refined-concrete", position = { x = 11, y = 4 } },
			{ name = "concrete",         position = { x = 11, y = 5 } },
			{ name = "concrete",         position = { x = 12, y = -5 } },
			{ name = "refined-concrete", position = { x = 12, y = -4 } },
			{ name = "refined-concrete", position = { x = 12, y = -3 } },
			{ name = "refined-concrete", position = { x = 12, y = -2 } },
			{ name = "refined-concrete", position = { x = 12, y = -1 } },
			{ name = "refined-concrete", position = { x = 12, y = 0 } },
			{ name = "refined-concrete", position = { x = 12, y = 1 } },
			{ name = "refined-concrete", position = { x = 12, y = 2 } },
			{ name = "refined-concrete", position = { x = 12, y = 3 } },
			{ name = "refined-concrete", position = { x = 12, y = 4 } },
			{ name = "concrete",         position = { x = 12, y = 5 } },
			{ name = "concrete",         position = { x = 13, y = -5 } },
			{ name = "concrete",         position = { x = 13, y = -4 } },
			{ name = "concrete",         position = { x = 13, y = -3 } },
			{ name = "concrete",         position = { x = 13, y = -2 } },
			{ name = "refined-concrete", position = { x = 13, y = -1 } },
			{ name = "refined-concrete", position = { x = 13, y = 0 } },
			{ name = "refined-concrete", position = { x = 13, y = 1 } },
			{ name = "concrete",         position = { x = 13, y = 2 } },
			{ name = "concrete",         position = { x = 13, y = 3 } },
			{ name = "concrete",         position = { x = 13, y = 4 } },
			{ name = "concrete", position = { x = 13, y = 5 } }
		}
	},
	resource_tiles = {
		enabled = false
	},
	resource_patches = {
		enabled = false,
	},
	resource_refill_nearby = {
		enabled = false
	}
}
